# Generated by Django 5.0.2 on 2024-02-13 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('pol', 'pol'), ('art', 'art'), ('art', 'tech'), ('trivia', 'trivia')], max_length=10)),
                ('region', models.CharField(choices=[('uk', 'uk'), ('eu', 'eu'), ('w', 'w')], max_length=2)),
                ('date', models.DateField()),
                ('details', models.TextField(max_length=128)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
